baseurl = "https://arc.tripl.ai/"
publishDir = "../docs"
languageCode = "en-us"
title = "Arc"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
pygmentsUseClasses=true

[params]
	# General information
	author = "ai.tripl.arc"
	description = "Arc is an opinionated framework for defining data pipelines which are predictable, repeatable and manageable."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/tripl-ai/arc"
	image = "ghcr.io/tripl-ai/arc"
	version = "3.3.0"
	arc_jupyter_image= "ghcr.io/tripl-ai/arc-jupyter"
	arc_jupyter_version = "3.4.0"
	spark_version = "3.0.1"
	scala_version = "2.12"
	hadoop_version = "3.2.0"
	arc_image_version = "1.0.0"
	arc_jupyter_image_version = "1.0.0"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	github  = "tripl-ai"

[[menu.main]]
 	name   = "Getting started"
 	url    = "getting-started/"
 	weight = 10

[[menu.main]]
	name   = "Tutorial"
	url    = "tutorial/"
	weight = 15

[[menu.main]]
	name   = "Extract"
	url    = "extract/"
	weight = 20

[[menu.main]]
	name   = "Transform"
	url    = "transform/"
	weight = 30

[[menu.main]]
	name   = "Load"
	url    = "load/"
	weight = 40

[[menu.main]]
	name   = "Execute"
	url    = "execute/"
	weight = 50

[[menu.main]]
	name   = "Validate"
	url    = "validate/"
	weight = 60

[[menu.main]]
	name   = "Schema"
	url    = "schema/"
	weight = 70

[[menu.main]]
	name   = "Deploy"
	url    = "deploy/"
	weight = 80

[[menu.main]]
	name   = "Security"
	url    = "security/"
	weight = 85

[[menu.main]]
	name   = "Plugins"
	url    = "plugins/"
	weight = 90

[[menu.main]]
	name   = "Common Solutions"
	url    = "solutions/"
	weight = 95

[[menu.main]]
	name   = "Change Log"
	url    = "changelog/"
	weight = 97

#[[menu.main]]
#	name   = "Contributing"
#	url    = "contributing/"
#	weight = 100

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 110

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true